# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-12 15:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleType', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=1000)),
                ('headline', models.CharField(max_length=1000)),
                ('body', models.CharField(max_length=1000000000000)),
                ('publicationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10000)),
                ('publicationDate', models.DateField()),
                ('email', models.CharField(max_length=254)),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNumber', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.UserAccount'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper.UserAccount'),
        ),
    ]
